trying to fix travis builds

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,84 +1,13 @@
+# errata:
+# - A travis bug causes caches to trample eachother when using the same
+#   compiler key (which we don't use anyway). This is worked around for now by
+#   replacing the "compilers" with a build name prefixed by the no-op ":"
+#   command. See: https://github.com/travis-ci/casher/issues/6
 os: linux
 language: cpp
 notifications:
-  slack: monetaryunit:C2TQNQk9Y2EdkcpMeK6RCacb
-env:
-  global:
-  - MAKEJOBS=-j3
-  - RUN_TESTS=false
-  - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
-  - CCACHE_SIZE=100M
-  - CCACHE_TEMPDIR=/tmp/.ccache-temp
-  - CCACHE_COMPRESS=1
-  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
-  - SDK_URL=https://dev.monetaryunit.tk/depends-sources/sdks
-cache:
-  apt: true
-  directories:
-  - depends/built
-  - depends/sdk-sources
-  - "$HOME/.ccache"
-matrix:
-  fast_finish: true
-  include:
-  - compiler: ": ARM"
-    env: HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="NO_QT=1"
-      GOAL="install" MONETARYUNIT_CONFIG="--enable-glibc-back-compat --enable-reduce-exports
-      "
-  - compiler: ": Win32"
-    env: HOST=i686-w64-mingw32 PACKAGES="nsis gcc-mingw-w64-i686 g++-mingw-w64-i686
-      binutils-mingw-w64-i686 mingw-w64-dev wine bc" RUN_TESTS=false GOAL="deploy"
-      MONETARYUNIT_CONFIG="--with-gui=qt5 --enable-reduce-exports " MAKEJOBS="-j2"
-  - compiler: ": 32-bit + dash"
-    env: HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc" RUN_TESTS=false GOAL="install"
-      MONETARYUNIT_CONFIG="--enable-reduce-exports --enable-glibc-back-compat  LDFLAGS=-static-libstdc++
-      " USE_SHELL="/bin/dash"
-  - compiler: ": Win64"
-    env: HOST=x86_64-w64-mingw32 PACKAGES="nsis gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
-      binutils-mingw-w64-x86-64 mingw-w64-dev wine bc" RUN_TESTS=false GOAL="deploy"
-      MONETARYUNIT_CONFIG="--enable-reduce-exports --with-gui=qt5 " MAKEJOBS="-j2"
-  - compiler: ": monetaryunitd"
-    env: HOST=x86_64-unknown-linux-gnu PACKAGES="bc" DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1"
-      RUN_TESTS=false GOAL="install" MONETARYUNIT_CONFIG="--enable-reduce-exports
-      --enable-glibc-back-compat  CPPFLAGS=-DDEBUG_LOCKORDER"
-  - compiler: ": No wallet"
-    env: HOST=x86_64-unknown-linux-gnu DEP_OPTS="NO_WALLET=1" RUN_TESTS=false GOAL="install"
-      MONETARYUNIT_CONFIG="--enable-reduce-exports --enable-glibc-back-compat "
-  - compiler: ": Cross-Mac"
-    env: HOST=x86_64-apple-darwin11 PACKAGES="cmake libcap-dev libz-dev libbz2-dev"
-      MONETARYUNIT_CONFIG="--enable-reduce-exports " OSX_SDK=10.9 GOAL="deploy"
-install:
-- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
-- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
-  --no-upgrade -qq $PACKAGES; fi
-before_script:
-- unset CC; unset CXX
-- mkdir -p depends/SDKs depends/sdk-sources
-- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
-  wget --no-check-certificate $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -O depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
-  fi
-- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
-  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-- make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
-script:
-- if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
-- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
-- MONETARYUNIT_CONFIG_ALL="--disable-tests --disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST
-  --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
-- depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
-- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export CCACHE_READONLY=1; fi
-- test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
-- "./configure --cache-file=config.cache $MONETARYUNIT_CONFIG_ALL $MONETARYUNIT_CONFIG
-  || ( cat config.log && false)"
-- make distdir PACKAGE=monetaryunit VERSION=$HOST
-- cd monetaryunit-$HOST
-- "./configure --cache-file=../config.cache $MONETARYUNIT_CONFIG_ALL $MONETARYUNIT_CONFIG
-  || ( cat config.log && false)"
-- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL
-  V=1 ; false )
-- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
-- if [ "$RUN_TESTS" = "true" ]; then make check; fi
-- if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.sh; fi
+  slack:
+    secure: mb2bj3QwJf+WOOI/gcFeQIGtzbrSlFqFzOIcht6bdQDG3c5hkiGjSx3HufYjKAh91nAu4AyBjI0d6R6fCfJVclU4UpRumpNhaui3/dTyV+7/IjIOKlgF72/4O04j47wBc+y7YA7N+6JxcWl1gdBwPOptVO1moSSEm/WlOTRRuAo=
 deploy:
   provider: releases
   skip_cleanup: true
@@ -91,3 +20,60 @@ deploy:
   on:
     repo: MonetaryUnit/MUE-Src
     tags: true
+env:
+  global:
+    - MAKEJOBS=-j3
+    - RUN_TESTS=false
+    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
+    - CCACHE_SIZE=100M
+    - CCACHE_TEMPDIR=/tmp/.ccache-temp
+    - CCACHE_COMPRESS=1
+    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
+    - SDK_URL=https://dev.monetaryunit.tk/depends-sources/sdks
+cache:
+  apt: true
+  directories:
+  - depends/built
+  - depends/sdk-sources
+  - $HOME/.ccache
+matrix:
+  fast_finish: true
+  include:
+    - compiler: ": ARM"
+      env: HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="NO_QT=1" GOAL="install" MONETARYUNIT_CONFIG="--enable-glibc-back-compat --enable-reduce-exports "
+    - compiler: ": Win32"
+      env: HOST=i686-w64-mingw32 PACKAGES="nsis gcc-mingw-w64-i686 g++-mingw-w64-i686 binutils-mingw-w64-i686 mingw-w64-dev wine bc" RUN_TESTS=false GOAL="deploy" MONETARYUNIT_CONFIG="--with-gui=qt5 --enable-reduce-exports " MAKEJOBS="-j2"
+    - compiler: ": 32-bit + dash"
+      env: HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc" RUN_TESTS=false GOAL="install" MONETARYUNIT_CONFIG="--enable-reduce-exports --enable-glibc-back-compat  LDFLAGS=-static-libstdc++ " USE_SHELL="/bin/dash"
+    - compiler: ": Win64"
+      env: HOST=x86_64-w64-mingw32 PACKAGES="nsis gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 mingw-w64-dev wine bc" RUN_TESTS=false GOAL="deploy" MONETARYUNIT_CONFIG="--enable-reduce-exports --with-gui=qt5 " MAKEJOBS="-j2"
+    - compiler: ": monetaryunitd"
+      env: HOST=x86_64-unknown-linux-gnu PACKAGES="bc" DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1" RUN_TESTS=false GOAL="install" MONETARYUNIT_CONFIG="--enable-reduce-exports --enable-glibc-back-compat  CPPFLAGS=-DDEBUG_LOCKORDER"
+    - compiler: ": No wallet"
+      env: HOST=x86_64-unknown-linux-gnu DEP_OPTS="NO_WALLET=1" RUN_TESTS=false GOAL="install" MONETARYUNIT_CONFIG="--enable-reduce-exports --enable-glibc-back-compat "
+    - compiler: ": Cross-Mac"
+      env: HOST=x86_64-apple-darwin11 PACKAGES="cmake libcap-dev libz-dev libbz2-dev" MONETARYUNIT_CONFIG="--enable-reduce-exports " OSX_SDK=10.9 GOAL="deploy"
+install:
+    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
+    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
+before_script:
+    - unset CC; unset CXX
+    - mkdir -p depends/SDKs depends/sdk-sources
+    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then wget --no-check-certificate $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -O depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+    - make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
+script:
+    - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
+    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
+    - MONETARYUNIT_CONFIG_ALL="--disable-tests --disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
+    - depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
+    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export CCACHE_READONLY=1; fi
+    - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
+    - ./configure --cache-file=config.cache $MONETARYUNIT_CONFIG_ALL $MONETARYUNIT_CONFIG || ( cat config.log && false)
+    - make distdir PACKAGE=monetaryunit VERSION=$HOST
+    - cd monetaryunit-$HOST
+    - ./configure --cache-file=../config.cache $MONETARYUNIT_CONFIG_ALL $MONETARYUNIT_CONFIG || ( cat config.log && false)
+    - make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )
+    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
+    - if [ "$RUN_TESTS" = "true" ]; then make check; fi
+    - if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.sh; fi
